### ISSUE TITLE
Ionic 4 compatibility

### ISSUE THREAD

**Issue by neroniaky** [toniantunovi/ion-bottom-drawer#6]
Thanks for creating a working bottom drawer component. Have been looking for one with with proper states for a long time!

Unfortunately this library does not support ionic 4, because they changed the package to `@ionic/angular` and the `Hammer` dependency is missing. Got it working by modifying the imports. Don't know if I will have the time to create an PR, though.

**Comment by INDOTMIS** [comment]
Is there any chance you could tell me which files you modified? This feature is perfect for what I need but not working on my version of Ionic as well.

**Comment by lincolnthree** [comment]
@neroniaky Hey! Do you think you could at least paste your updated code here? That would be super helpful!

**Comment by zmarwa** [comment]
Hello, For me it works with adding: 
npm install --save hammerjs
npm install --save @types/hammerjs

and change imports like 'ionic-angular' with '@ionic/angular'

**Comment by zmarwa** [comment]
Hello, It works for development mode. But when trying to build a production release:
ionic cordova build --release --prod android
compile fails with: 

```
ERROR in ../ion-bottom-drawer/ion-bottom-drawer.ts(7,13): Error during template compile of 'IonBottomDrawerModule'
  Could not resolve ionic-angular relative to [object Object]..
```
Any idea ?

**Comment by kapilraghuwanshi** [comment]
> Hello, For me it works with:
> 
> * install hammers
>   npm install --save hammerjs
>   npm install --save @types/hammerjs
> * import hammerjs into page.ts
>   import 'hammerjs';
> * change alls imports like
>   import { Platform, DomController, IonicModule } from 'ionic-angular';
>   with
>   import { Platform, DomController, IonicModule } from '@ionic/angular' ;

Thank you for this.

**Comment by kapilraghuwanshi** [comment]
What if I just want - on every pan up/pan down, it should bounce to top/bottom only, no middle position to stay. How can I achieve this? @toniantunovi 

Anyways, shouldBounce flag is not working in ionic 4 also.

**Comment by toniantunovi** [comment]
Hi, to achive the effect where there is no middle position just set minimumHeight and dockedHeight to 0. 

I've implemented this for a hobby project of mine so I don't have much time for it. I will support ionic 4 when and if I decide to migrate this project to ionic 4.

**Comment by kapilraghuwanshi** [comment]
@toniantunovi
It was not working as expected.

Since there are translateY function, we won't be able to achieve always top or bottom. Can you please help me to modify. Code {remove 3 2 other states, no translate Y method}. If user slides it should be at the top or if he slide down then it the bottom.

**Comment by MHzarini** [comment]
i have created another repo based on this with support for ionic 4

https://github.com/MHzarini/ion-bottom-nav-drawer

Sorry @toniantunovi but i need it ASAP.

Please, let me know if you have any comments/notices.

**Comment by Justinio99** [comment]
@MHzarini thanks for providing this module. :) Could you please remove the console.log from ion-bottom-nav-drawer.js:249. My console is full with values. 
Thanks alot!

**Comment by toniantunovi** [comment]
I've implemented support for Ionic 4 so I'm closing this issue.

**Comment by alex1kariuki** [comment]
Hey it still isn't working for me on ionic 4. The screenshot below has some of the error details.
<img width="742" alt="Screenshot 2019-06-19 at 15 15 48" src="https://user-images.githubusercontent.com/22114609/59764774-26d0fb80-92a5-11e9-82ae-dedf71ee214b.png">
